// Code generated by MockGen. DO NOT EDIT.
// Source: resource_service.go

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"
	resources "github.com/stsg/gophkeeper2/client/model/resources"
	model "github.com/stsg/gophkeeper2/server/model"
	enum "github.com/stsg/gophkeeper2/pkg/model/enum"

	gomock "github.com/golang/mock/gomock"
)

// MockResourceService is a mock of ResourceService interface.
type MockResourceService struct {
	ctrl     *gomock.Controller
	recorder *MockResourceServiceMockRecorder
}

// MockResourceServiceMockRecorder is the mock recorder for MockResourceService.
type MockResourceServiceMockRecorder struct {
	mock *MockResourceService
}

// NewMockResourceService creates a new mock instance.
func NewMockResourceService(ctrl *gomock.Controller) *MockResourceService {
	mock := &MockResourceService{ctrl: ctrl}
	mock.recorder = &MockResourceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceService) EXPECT() *MockResourceServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockResourceService) Delete(ctx context.Context, resId int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockResourceServiceMockRecorder) Delete(ctx, resId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockResourceService)(nil).Delete), ctx, resId)
}

// Get mocks base method.
func (m *MockResourceService) Get(ctx context.Context, resId int32) (*resources.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resId)
	ret0, _ := ret[0].(*resources.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockResourceServiceMockRecorder) Get(ctx, resId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockResourceService)(nil).Get), ctx, resId)
}

// GetDescriptions mocks base method.
func (m *MockResourceService) GetDescriptions(ctx context.Context, resType enum.ResourceType) ([]*model.ResourceDescription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDescriptions", ctx, resType)
	ret0, _ := ret[0].([]*model.ResourceDescription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDescriptions indicates an expected call of GetDescriptions.
func (mr *MockResourceServiceMockRecorder) GetDescriptions(ctx, resType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDescriptions", reflect.TypeOf((*MockResourceService)(nil).GetDescriptions), ctx, resType)
}

// GetFile mocks base method.
func (m *MockResourceService) GetFile(ctx context.Context, resId int32) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", ctx, resId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockResourceServiceMockRecorder) GetFile(ctx, resId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockResourceService)(nil).GetFile), ctx, resId)
}

// Save mocks base method.
func (m *MockResourceService) Save(ctx context.Context, resType enum.ResourceType, data, meta []byte) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, resType, data, meta)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockResourceServiceMockRecorder) Save(ctx, resType, data, meta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockResourceService)(nil).Save), ctx, resType, data, meta)
}

// SaveFile mocks base method.
func (m *MockResourceService) SaveFile(ctx context.Context, path string, meta []byte) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFile", ctx, path, meta)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveFile indicates an expected call of SaveFile.
func (mr *MockResourceServiceMockRecorder) SaveFile(ctx, path, meta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFile", reflect.TypeOf((*MockResourceService)(nil).SaveFile), ctx, path, meta)
}

// Update mocks base method.
func (m *MockResourceService) Update(ctx context.Context, resId int32, resType enum.ResourceType, data, meta []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, resId, resType, data, meta)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockResourceServiceMockRecorder) Update(ctx, resId, resType, data, meta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockResourceService)(nil).Update), ctx, resId, resType, data, meta)
}
