// Code generated by MockGen. DO NOT EDIT.
// Source: token_processing.go

// Package interceptors is a generated GoMock package.
package interceptors

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockRequestTokenProcessor is a mock of RequestTokenProcessor interface.
type MockRequestTokenProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockRequestTokenProcessorMockRecorder
}

// MockRequestTokenProcessorMockRecorder is the mock recorder for MockRequestTokenProcessor.
type MockRequestTokenProcessorMockRecorder struct {
	mock *MockRequestTokenProcessor
}

// NewMockRequestTokenProcessor creates a new mock instance.
func NewMockRequestTokenProcessor(ctrl *gomock.Controller) *MockRequestTokenProcessor {
	mock := &MockRequestTokenProcessor{ctrl: ctrl}
	mock.recorder = &MockRequestTokenProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestTokenProcessor) EXPECT() *MockRequestTokenProcessorMockRecorder {
	return m.recorder
}

// TokenInterceptor mocks base method.
func (m *MockRequestTokenProcessor) TokenInterceptor() grpc.UnaryClientInterceptor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenInterceptor")
	ret0, _ := ret[0].(grpc.UnaryClientInterceptor)
	return ret0
}

// TokenInterceptor indicates an expected call of TokenInterceptor.
func (mr *MockRequestTokenProcessorMockRecorder) TokenInterceptor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenInterceptor", reflect.TypeOf((*MockRequestTokenProcessor)(nil).TokenInterceptor))
}

// TokenStreamInterceptor mocks base method.
func (m *MockRequestTokenProcessor) TokenStreamInterceptor() grpc.StreamClientInterceptor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenStreamInterceptor")
	ret0, _ := ret[0].(grpc.StreamClientInterceptor)
	return ret0
}

// TokenStreamInterceptor indicates an expected call of TokenStreamInterceptor.
func (mr *MockRequestTokenProcessorMockRecorder) TokenStreamInterceptor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenStreamInterceptor", reflect.TypeOf((*MockRequestTokenProcessor)(nil).TokenStreamInterceptor))
}
